/// @description Init vars

if(player_deck){
	cards_in_deck = [
		"Water Dagger",
		"Water Dagger",
		"The Sacred Spring",
		"The Sacred Spring",
		"Fireball",
		"Fireball",
		"Spreading Flame",
		"Spreading Flame",
		"Spring Water",
		"Spring Water",
		"Pot of Greed",
		"Pot of Greed",
		"Verdant Codex",
		"Verdant Codex",
		"Sirens Echo Mk. IV",
		"Sirens Echo Mk. IV",
		"Holy Water Balloon",
		"Holy Water Balloon",
		"Tidal Wave",
		"Tidal Wave",
		"Tidal Wave",
		"Tidal Wave",
	]
}else{
	cards_in_deck = [
		"Fire Dagger",
		"Fire Dagger",
		"Fire Dagger",
		"Fire Dagger",
		"Fireball",
		"Fireball",
		"Fireball",
		"Fireball",
		"Spreading Flame",
		"Spreading Flame",
		"Spreading Flame",
		"Spreading Flame",
		"Spring Water",
		"Spring Water",
		"Spring Water",
		"Spring Water",
		"Pot of Greed",
		"Pot of Greed",
		"Pot of Greed",
		"Pot of Greed",
		"Verdant Codex",
		"Verdant Codex",
		"Verdant Codex",
		"Verdant Codex",
	]
}
deck_size = array_length(cards_in_deck)