/// @description Init vars

if(player_deck){
	cards_in_deck = [
		"Water Dagger",
		"Water Dagger",
		"The Sacred Spring",
		"The Sacred Spring",
		"Fireball",
		"Fireball",
		"Spreading Flame",
		"Spreading Flame",
		"Spring Water",
		"Spring Water",
		"Pot of Greed",
		"Pot of Greed",
		"Verdant Codex",
		"Verdant Codex",
		"Sirens Echo Mk. IV",
		"Sirens Echo Mk. IV",
		"Holy Water Balloon",
		"Holy Water Balloon",
		"Tidal Wave",
		"Tidal Wave",
		"Pressure",
		"Celestial Shower",
		"Celestial Shower",
		"Love Potion of Calming Mind",
		"Love Potion of Calming Mind",
	]
}else{
	if(cpu_name == "Mid"){
		cards_in_deck = [
			"Fire Dagger",
			"Fire Dagger",
			"Fire Dagger",
			"Fire Dagger",
			"Fireball",
			"Fireball",
			"Fireball",
			"Fireball",
			"Spreading Flame",
			"Spreading Flame",
			"Spring Water",
			"Spring Water",
			"Spring Water",
			"Spring Water",
			"Pot of Greed",
			"Pot of Greed",
			"Pot of Greed",
			"Pot of Greed",
			"Verdant Codex",
			"Verdant Codex",
			"Verdant Codex",
			"Verdant Codex",
			"Celestial Shower",
			"Celestial Shower",
			"Celestial Shower",
			"Celestial Shower",
		]
	}
	if(cpu_name == "Great"){
		cards_in_deck = [
			"Fire Dagger",
			"Fire Dagger",
			"Fire Dagger",
			"Fire Dagger",
			"Fireball",
			"Fireball",
			"Fireball",
			"Fireball",
			"Spreading Flame",
			"Spreading Flame",
			"Spreading Flame",
			"Spreading Flame",
			"Spring Water",
			"Spring Water",
			"Spring Water",
			"Spring Water",
			"Pot of Greed",
			"Pot of Greed",
			"Celestial Shower",
		]
	}
}
deck_size = array_length(cards_in_deck)